repos:
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: tox
        language: system
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.4.2
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
