repos:
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: tox -e py37
        language: system
      - id: pylint
        name: pylint
        entry: python3 -m pylint.__main__
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
