repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python3 -m pylint.__main__
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
