language: python
matrix:
  fast_finish: true
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=lint
install: pip install -U tox-travis coveralls
script: tox
cache: pip
after_success: coveralls
deploy:
  provider: pypi
  user: Limych
  password:
    secure: 0T08gppSMCnmtRrmwIrkgF4VaKk6E0NPW4MQzNnNsQ2lj8MoKX2dtNlxgbD9sLeVjyxWVJhDZmNUiOF80r1YFL2LL40a2peYNzBPoH2qaQrq5FVUuG0oXzfTPDk0mh4ZTdRxC1S/NWQ4dbubUusG0bxIGxBiVkEOuxwwAs62+m9nNc+eDoAX4l7tLyIkECXypbgKXkELLo46PH9pJG7ug/nkZ2YvM/pt+pvFLRzLOIoT+8h4GbLoQUaDfymgd7l1Oi/cA44paWXPeSHpQIgsyLACZmObDL+tFm25/qvxRtDrFh+bKNJb0GHf11EvnJyeI9/Qh701rC9X9g8duWQrRLQ/bugbnaJZHWlEEAU2tGlr7NscC7p85GgcwHV0uSoevCm4xZUxzlrPZ3iR8JQDYGa7c9pg/w/onL3hmZL+amkCslFCnDJ0HdFvbRJE7msGOsr1vyRGOXLLaAeUqLKpvcdYDsX/uOqrfErIJ6nda38+igRSqxaU+3kvkOLVmq7crNlYtDlChabu142iE3o3Ap1zWG9KlJDoD0YTnxh2Zp2I48zmf6tqEeRnbHER/M94HVL30yM4N66rQdzgS67po0lUoX2Fm0q7mAEd7Ma6k5JEJH7sZYovJplXBhP28IniKKf3A67hGZ5sNjgFuJFzp9D35e8w+2r7kFGGpqV+La8=
  on:
    branch: master
