language: python
matrix:
  fast_finish: true
  include:
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=lint
install: pip install -U tox-travis coveralls
script: tox
cache: pip
after_success: coveralls
deploy:
  provider: pypi
  user: Limych
  password:
    secure: HerERVWrqdp+J1sGi0Fl7A0zj0rNdt0zMOfvmbOlxe55PYkSLAz5reZbZI4ozVTSb8KGfpGYfZmT8PrSs09C5qkMfPVDUqVXaKH2rePGW8pHK9zjGx1b+yau1Ix9jKFXdgeM1xO+3qEuOMGkxubtASby339XXWN0gLHyI6bZCNM81herr1b5tjYp+rx4pu9axykPZbVzkcs3+ukqOVh6WxYdUP++JcGmss7tMWtovqQnu4rTC0eo0FESJSUbq8uY97qKi4dM6XZIK9DIVDM7ykPEqRVryZlVmaVy9W7lGeCA559ya9Lz9dPDvw4AsQAfsCv8pYG9tKNqtMECihGut4diqI0z47FUiIO5PDPcz6bPpXRtPTNG5HZ/GcpyV7KumhecPZ3ooQbJzjliafyYU2nsRw/32hg6H6H+bsFfTym/VKk0ELt8PCxasr6tVqsBJNStwkBCJ2mgV7At3X+MTClEO+yLfnB81Q2b2XUqIoAyCMOvCR5pGEAD6k1u1YnzQ/G0EkUvP4AMuo6Vd3mnHG88XFt/eLaBUSeciy630LyPttysjzyh8GOqMecZRScb8jZZWELKabPDsWP659pScvDQ3OD3J3CGEosUOYcSN8QttmB9D8qWjFDf04hYCe/Unfq0JBh7O5f0l5Zlb7JuO7olNrqWSErLFqTzU1AUmu4=
  on:
    branch: master
